---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alert-recommender-pipeline.fullname" . }}-minio
  labels:
    {{- include "alert-recommender-pipeline.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.minio.accessKey | quote }}
  secret-key: {{ .Values.minio.secretKey | quote }}
  endpoint: {{ .Values.minio.endpoint | quote }}
  bucket: {{ .Values.minio.bucketName | quote }}
