{{- if and (not .Values.admin.existingSecret) .Values.admin.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.admin.existingSecretKey }}: {{ .Values.admin.password | b64enc | quote }}
{{- end }}

