{{- if index .Values "model-registry" "enabled" }}
{{- $mrNamespace := index .Values "model-registry" "namespace" | default .Release.Namespace }}
{{- if ne $mrNamespace .Release.Namespace }}
---
# Create the model-registry namespace if it's different from the release namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $mrNamespace }}
  labels:
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
{{- end }}
{{- end }}
