{{- if and .Values.smtp4dev.enabled .Values.smtp4dev.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.smtp4dev.name }}
  labels:
    app: {{ .Values.smtp4dev.name }}
  {{- with .Values.smtp4dev.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.smtp4dev.route.host }}
  host: {{ .Values.smtp4dev.route.host }}
  {{- end }}
  {{- if .Values.smtp4dev.route.tls.enabled }}
  tls:
    termination: {{ .Values.smtp4dev.route.tls.termination }}
    {{- if .Values.smtp4dev.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.smtp4dev.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.smtp4dev.name }}
    weight: 100
  port:
    targetPort: web
  wildcardPolicy: None
{{- end }}